-- MySQL 8.0.16+; 9 business tables used by the current WAVE Music scope.
-- Only run this file in a fresh project database (CREATE TABLE IF NOT EXISTS).
CREATE DATABASE IF NOT EXISTS wave_music_mvc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE wave_music_mvc;

CREATE TABLE IF NOT EXISTS NguoiDung (
  MaNguoiDung INT AUTO_INCREMENT PRIMARY KEY,
  HoTen VARCHAR(100) NOT NULL,
  Email VARCHAR(150) NOT NULL UNIQUE,
  MatKhau VARCHAR(255) NOT NULL,
  AnhDaiDien VARCHAR(255) NULL,
  VaiTro VARCHAR(20) NOT NULL DEFAULT 'USER',
  TrangThaiVIP BOOLEAN NOT NULL DEFAULT FALSE,
  NgayDangKy DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_vaitro CHECK (VaiTro IN ('USER', 'ADMIN'))
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CaSi (
  MaCaSi INT AUTO_INCREMENT PRIMARY KEY,
  TenCaSi VARCHAR(150) NOT NULL,
  HinhAnh VARCHAR(255) NULL,
  MoTa TEXT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TheLoai (
  MaTheLoai INT AUTO_INCREMENT PRIMARY KEY,
  TenTheLoai VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Album (
  MaAlbum INT AUTO_INCREMENT PRIMARY KEY,
  TenAlbum VARCHAR(200) NOT NULL,
  MaCaSi INT NOT NULL,
  AnhAlbum VARCHAR(255) NULL,
  CONSTRAINT fk_album_casi FOREIGN KEY (MaCaSi) REFERENCES CaSi(MaCaSi)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BaiHat (
  MaBaiHat INT AUTO_INCREMENT PRIMARY KEY,
  TenBaiHat VARCHAR(200) NOT NULL,
  MaCaSi INT NOT NULL,
  MaTheLoai INT NOT NULL,
  MaAlbum INT NULL,
  AnhBia VARCHAR(255) NULL,
  DuongDanAudio VARCHAR(255) NOT NULL,
  ThoiLuong INT NOT NULL,
  IsVIP BOOLEAN NOT NULL DEFAULT FALSE,
  TrangThai BOOLEAN NOT NULL DEFAULT TRUE,
  LuotNghe INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_baihat_casi FOREIGN KEY (MaCaSi) REFERENCES CaSi(MaCaSi)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_baihat_theloai FOREIGN KEY (MaTheLoai) REFERENCES TheLoai(MaTheLoai)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_baihat_album FOREIGN KEY (MaAlbum) REFERENCES Album(MaAlbum)
    ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT chk_thoiluong CHECK (ThoiLuong > 0),
  CONSTRAINT chk_luotnghe CHECK (LuotNghe >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Playlist (
  MaPlaylist INT AUTO_INCREMENT PRIMARY KEY,
  TenPlaylist VARCHAR(150) NOT NULL,
  MaNguoiDung INT NOT NULL,
  NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_playlist_nguoidung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ChiTietPlaylist (
  MaPlaylist INT NOT NULL,
  MaBaiHat INT NOT NULL,
  NgayThem DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (MaPlaylist, MaBaiHat),
  CONSTRAINT fk_ctplaylist_playlist FOREIGN KEY (MaPlaylist) REFERENCES Playlist(MaPlaylist)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_ctplaylist_baihat FOREIGN KEY (MaBaiHat) REFERENCES BaiHat(MaBaiHat)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS GoiVIP (
  MaGoi INT AUTO_INCREMENT PRIMARY KEY,
  TenGoi VARCHAR(100) NOT NULL,
  ThoiHan INT NOT NULL,
  Gia DECIMAL(12,2) NOT NULL,
  MoTa TEXT NULL,
  CONSTRAINT chk_goivip_thoihan CHECK (ThoiHan > 0),
  CONSTRAINT chk_goivip_gia CHECK (Gia >= 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DangKyVIP (
  MaDangKy INT AUTO_INCREMENT PRIMARY KEY,
  MaNguoiDung INT NOT NULL,
  MaGoi INT NOT NULL,
  NgayBatDau DATETIME NOT NULL,
  NgayKetThuc DATETIME NOT NULL,
  TrangThai VARCHAR(30) NOT NULL DEFAULT 'CHO_XAC_NHAN',
  CONSTRAINT fk_dangkyvip_nguoidung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_dangkyvip_goi FOREIGN KEY (MaGoi) REFERENCES GoiVIP(MaGoi)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_vip_dates CHECK (NgayKetThuc > NgayBatDau),
  CONSTRAINT chk_vip_status CHECK (TrangThai IN ('CHO_XAC_NHAN','DA_XAC_NHAN','HUY')),
  INDEX idx_vip_lookup (MaNguoiDung, TrangThai, NgayBatDau, NgayKetThuc)
) ENGINE=InnoDB;
